---

- name: Restart InfluxDB
  service:
    name: influxdb
    state: restarted

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Reconfigure Grafana
  include: grafana_reset.yml
